/**
 * Regression test for inventory-service
 * Generated by Subagent Beta (QA Agent) at 2026-05-16T17:16:18.881Z
 * Fixed Bug: CM-003 — inventory-service
 *
 * This test ensures the service remains healthy after the Chaos Monkey fix.
 * Run: node services/inventory-service/tests/regression.test.js
 */

'use strict';

const http = require('http');

const SERVICE_NAME = 'inventory-service';
const PORT = 3103;
let passed = 0;
let failed = 0;

function httpGet(port, urlPath) {
  return new Promise((resolve, reject) => {
    const req = http.request({ hostname: 'localhost', port, path: urlPath, method: 'GET', timeout: 5000 }, (res) => {
      let data = '';
      res.on('data', chunk => { data += chunk; });
      res.on('end', () => {
        try { resolve({ status: res.statusCode, body: JSON.parse(data) }); }
        catch { resolve({ status: res.statusCode, body: {} }); }
      });
    });
    req.on('error', reject);
    req.on('timeout', () => { req.destroy(); reject(new Error('Timeout')); });
    req.end();
  });
}

async function assert(testName, fn) {
  try {
    await fn();
    console.log(`  ✅ PASS: ${testName}`);
    passed++;
  } catch (err) {
    console.error(`  ❌ FAIL: ${testName} — ${err.message}`);
    failed++;
  }
}

function assertEqual(actual, expected, label) {
  if (actual !== expected) {
    throw new Error(`${label}: expected "${expected}", got "${actual}"`);
  }
}

function assertExists(value, label) {
  if (value === undefined || value === null) {
    throw new Error(`${label}: expected a value, got ${value}`);
  }
}

async function runTests() {
  console.log(`\n🧪 Regression Tests: ${SERVICE_NAME}`);
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');

  // Test 1: Health endpoint returns 200
  await assert('GET /health returns HTTP 200', async () => {
    const res = await httpGet(PORT, '/health');
    assertEqual(res.status, 200, 'HTTP status');
  });

  // Test 2: Health response has HEALTHY status
  await assert('GET /health returns HEALTHY status', async () => {
    const res = await httpGet(PORT, '/health');
    assertEqual(res.body.status, 'HEALTHY', 'status field');
  });

  // Test 3: Health response includes service name
  await assert('GET /health includes service name', async () => {
    const res = await httpGet(PORT, '/health');
    assertEqual(res.body.service, SERVICE_NAME, 'service field');
  });

  // Test 4: Health response includes port
  await assert('GET /health includes correct port', async () => {
    const res = await httpGet(PORT, '/health');
    assertEqual(res.body.port, PORT, 'port field');
  });

  // Test 5: Work endpoint returns 200
  await assert('GET /work returns HTTP 200', async () => {
    const res = await httpGet(PORT, '/work');
    assertEqual(res.status, 200, 'HTTP status');
  });

  // Test 6: Work endpoint returns success
  await assert('GET /work returns success: true', async () => {
    const res = await httpGet(PORT, '/work');
    assertEqual(res.body.success, true, 'success field');
  });

  // Test 7: Bug-type-specific regression check
  // Bug: CM-003 — inventory-service
  await assert('Regression: Service not affected by CM-003', async () => {
    const res = await httpGet(PORT, '/health');
    // Ensure the status is not CRITICAL (would indicate CM-003 logic error)
    if (res.body.status === 'CRITICAL') {
      throw new Error('Status is CRITICAL — CM-003 logic error may still be present');
    }
    // Ensure we got a valid response (not a parse error — would indicate CM-001)
    assertExists(res.body.status, 'status');
  });

  // Summary
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log(`Results: ${passed} passed, ${failed} failed`);

  if (failed > 0) {
    console.error(`\n❌ REGRESSION DETECTED in ${SERVICE_NAME}!`);
    process.exit(1);
  } else {
    console.log(`\n✅ All regression tests passed for ${SERVICE_NAME}`);
    process.exit(0);
  }
}

runTests().catch(err => {
  console.error('Test runner error:', err.message);
  console.error('Make sure the service is running on port ' + PORT);
  process.exit(1);
});
